registration_form/registrationapp/urls.py
from django.urls import path, include
from registrationapp import views

app_name = 'registrationapp'

urlpatterns=[
    path('register/', views.register, name="register"),
    path('user_login/', views.user_login, name='user_login'),
]

registration_form/registrationapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username




# Create your models here.

registration_form/registrationapp/forms.py
from django import forms
from django.contrib.auth.models import User
from registrationapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

registration_form/registrationapp/views.py
from django.shortcuts import render
from registrationapp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login ,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'registrationapp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpRespons("You Are LOGGED IN !!")

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'registrationapp/registration.html',
                                {'user_form': user_form,
                                'profile_form':profile_form,
                                'registered':registered})



def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and faild!")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("INVALID CREDENTIALS")
    else:
        return render(request, 'registrationapp/login.html', {})

registration_form/templates/registrationapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="nac navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'registrationapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="nav-link" href="{% url 'registrationapp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
<!-- here will be stuff outside inherited base -->
      {% endblock %}
    </div>

  </body>
</html>

registration_form/templates/registrationapp/index.html
<!DOCTYPE html>
{% extends 'registrationapp/base.html' %}
{% block body_block%}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>
{% endblock %}

registration_form/templates/registrationapp/login.html
<!DOCTYPE html>
{% extends 'registrationapp/base.html' %}
{% load staticfiles %}
{% block body_block%}

<div class="jumbotron">
  <h1>Please login!</h1>
    <form class="{% url 'registrationapp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password</label>
      <input type="password" name="password">
      <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

registration_form/templates/registrationapp/registration.html
<!DOCTYPE html>
{% extends 'registrationapp/base.html' %}
{% load staticfiles %}
{% block body_block%}

<div class="jumbotron">
  {% if register %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register here!</h1>
  <h3>Fill out the form: </h3>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
</div>

{% endblock %}